server:
spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/flight_booking_db
    username: root
    password: Sahil@2846
  jpa:
    hibernate:
      ddl-auto: 5
flight-service:
  url: http://flight-service:8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
