server:
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/flight_booking_db
    username: root
    password: Sahil@2846
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
